apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - ../../base/n8n
  - database.yaml
  - n8n-http-route.yaml
patches:
  - path: n8n-values.yaml
    target:
      kind: HelmRelease
