apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
  # 1
  - cilium
  - linstor
  # 2
  - external-secrets
  - cert-manager
  - csi-nfs
  - vaultwarden
  - cloudnative-pg
  - bitwarden-cli
  # - istio
  - envoy-gateway
  # 3
  - victoria-metrics
  - victoria-logs
  - blackbox-exporter
  - external-dns
  - ../base/metrics-server
  - misc
  