apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-nfs
resources:
  - ../../../../apps/base/csi-nfs
  - namespace.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
