apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system
resources:
  - gw-class.yaml
  - gw-internal.yaml
  - gw-external.yaml
  - vm-podscrape.yaml
configMapGenerator:
  - name: envoy-gateway-dashboards
    namespace: envoy-gateway-system
    files:
      - dashboards/envoy-clusters.json
      - dashboards/envoy-gateway-global.json
      - dashboards/envoy-proxy-global.json
      - dashboards/resources-monitor.gen.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: envoy-gateway
        app.kubernetes.io/component: envoy-gateway
        kustomize.toolkit.fluxcd.io/substitute: disabled
