apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linstor
resources:
  - storage-class.yaml
  - linstor-cluster.yaml
  - satelite-config.yaml
  - namespace.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
  - path: git-repos.yaml
    target:
      kind: GitRepository
