apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../../../apps/base/cert-manager
  - cluster-certificate.yaml
  - cluster-issuer.yaml
  - secrets.yaml
  - reference-grant.yaml
  - namespace.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
