apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: bitwarden-cli
resources:
  - bitwarden-cli.yaml
  - network-policy.yaml
  - namespace.yaml
secretGenerator:
  - name: bitwarden-cli
    envs:
      - secret.enc.env
  - name: registry-credentials
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=registry-creds.enc.json
