apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - ../../../../apps/base/open-webui
  - open-webui-http-route.yaml
patches:
  - path: open-webui-values.yaml
    target:
      kind: HelmRelease
