apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ../../base/external-dns
  - secrets.yaml
  - namespace.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: helm-release-public.yaml
    target:
      kind: HelmRelease
configMapGenerator:
  - name: external-dns-dashboards
    namespace: external-dns
    files:
      - edns-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: external-dns
        app.kubernetes.io/component: external-dns
        kustomize.toolkit.fluxcd.io/substitute: disabled
