apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../../apps/base/blackbox-exporter
  - vmrule.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
configMapGenerator:
  - name: blackbox-exporter-dashboards
    namespace: monitoring
    files:
      - blackbox-exporter.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: blackbox-exporter
        app.kubernetes.io/component: blackbox-exporter
        kustomize.toolkit.fluxcd.io/substitute: disabled
