apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
  - ../../base/cloudnative-pg
  - ../../base/envoy-gateway
  - ../../base/n8n
  - ../../base/podinfo
patchesStrategicMerge:
  - dev-flex.yaml
