apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base/cilium
  - pool.yaml
  - hubble-http-route.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease