apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mattermost
  namespace: homelab
spec:
  chart:
    spec:
      version: "6.6.x"
  test:
    enable: false
  values:
    image:
      repository: homelab.cr.cloud.ru/mattermost
    persistence:
      data:
        enabled: false
      plugins:
        enabled: false
    mysql:
      enabled: false
    externalDB:
      enabled: true
    extraEnvVars:
      - name: MM_SQLSETTINGS_DATASOURCE
        valueFrom:
          secretKeyRef:
            name: mattermost-db-app
            key: uri
