apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/bundles/dev-flex
  - ../namespaces.yaml
  - cert-manager
  - cloudnative-pg
  - istio
  - n8n
  - podinfo
  - victoria-metrics
