apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/prometheus-crds
  - ../base/victoria-metrics
  - ../base/cloudnative-pg
  - ../base/gateway-api
  - ../base/envoy-gateway
