apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gw-internal.yaml
  - gw-configmap.yaml
  - namespace.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
