apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - ../../base/mattermost
  - database.yaml
  - networkpolicy.yaml
  - mattermost-http-route.yaml
patches:
  - path: mattermost-values.yaml
    target:
      kind: HelmRelease
