apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - ../../../../apps/base/qbittorrent
  - http-route.yaml
  - networkpolicy.yaml
  - pvc.yaml
patches:
  - path: path.yaml
    target:
      kind: Deployment
