apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - pv.yaml
  - pvc.yaml
  - ../../../../apps/base/immich
  - vmprobe.yaml
  - database.yaml
  - immich-http-route.yaml
  - networkpolicy.yaml
patches:
  - path: immich-values.yaml
    target:
      kind: HelmRelease
