---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - vmrule.yaml
  - namespace.yaml
configMapGenerator:
  - name: cnpg-dashboard
    files:
      - cnpg-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: cloudnative-pg
        app.kubernetes.io/component: cloudnative-pg
        kustomize.toolkit.fluxcd.io/substitute: disabled
