apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/cloudnative-pg
  - ../base/csi-nfs
  - ../base/external-secrets
  - ../base/linstor
  - ../base/prometheus-crds
  - ../base/victoria-metrics
  - ../base/gateway-api
  # - ../base/istio
