adminToken:
    value: ENC[AES256_GCM,data:HhM6u8Do9gBLRAF96FcZtH3BfBWveJ1NkDUN9bO3SYxSUPeN,iv:fk+AXDAlFHlVXc0lPqgG8LyFFo/B9k2ylvNauov6V4U=,tag:IxU5cjRF+Uq7oRzhMrrG8A==,type:str]
sops:
    age:
        - recipient: age1e0wp4sq3nsdgnaqf97mqzssffj66mtu9jpvmv23f5m927xkjvufsate277
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bDNlcVNVK0ZNQjBhMlBQ
            UXEwb3ZmeGVTdVBxSC91KzhLeVNQSGxaNVg0CjF4aDFtVmhaTk1nQ09BV0RLR05L
            ZkRORVpQVmNCeS9Vc1ZwRzJDWU1zSzAKLS0tIEVkcWdicEZlWjVUcENrZnQ1VzFS
            ZzZPQlRWM1FvdENnQjdQcVdOV1oxaXcKv3HU5NxzTdFJxe2f83G740Lk1bmtnQ3M
            Tp/YWY6uMRfo5Z1QlVTcK24kW9egSJbyuL8QC5KhgKEys+QkE/5Sjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T18:12:15Z"
    mac: ENC[AES256_GCM,data:s73mkmtQinDmZtDrqRBo/apKRDZ8xfk3vgTDNewjgnVnVah5tE6LhFMn7AvEo71gy3UCCYxrA7js+d8l1AeRTfisLh6POdjtjKi58caYKKzs2FUNuoKa4l+XS8lQ+VwMArv9LGZRH0HkIeFYnEKj1zRtbG8k4f4fZAc+MjFvuxA=,iv:N5rwVFDLaobxvZFvzo7/ojNv6r36CFKMpRb6Zn6tWmU=,tag:Qg9eLW1zX3E6ufZunT6QSQ==,type:str]
    encrypted_regex: ^(data|stringData|value)$
    version: 3.10.2
