apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - ../../../../apps/base/podinfo
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
