apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  # - grafana-dashboardDefinitions.yaml
  - helm-repo.yaml
  - secrets.yaml
  - ../../base/victoria-metrics
  - grafana-http-route.yaml
  - vmsingle-http-route.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
