apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - pv.yaml
  - pvc.yaml
  - jellyfin-http-route.yaml
  - networkpolicy.yaml
patches:
  - path: jellyfin-values.yaml
    target:
      kind: HelmRelease
