apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - pv.yaml
  - pvc.yaml
  - vmprobe.yaml
  - database.yaml
  - immich-http-route.yaml
  - networkpolicy.yaml
