apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/victoria-logs
  - datasource.yaml
  - victoria-logs-http-route.yaml
patches:
  - path: helm-release.yaml
    target:
      kind: HelmRelease
